name: Learning

on: 
  push:
    branches:
      - dev

jobs:
  hey:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hey"
  lint-code:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      - name: preparing
      - uses: actions/checkout@v2

      - name: run super-linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
